/**
 * SQL DDL Generator for SchemaVis
 * Generates dialect-aware CREATE TABLE statements from a Diagram.
 */
import { DatabaseType } from "./domain/database-type";
import type { DBCustomType } from "./domain/db-custom-type";
import { DBCustomTypeKind } from "./domain/db-custom-type";
import type { DBField } from "./domain/db-field";
import type { DBRelationship } from "./domain/db-relationship";
import type { DBTable } from "./domain/db-table";
import type { Diagram } from "./domain/diagram";

export interface GenerateSQLOptions {
  databaseType?: DatabaseType;
  includeIndexes?: boolean;
  includeForeignKeys?: boolean;
  includeCustomTypes?: boolean;
}

const DEFAULT_OPTIONS: GenerateSQLOptions = {
  includeIndexes: true,
  includeForeignKeys: true,
  includeCustomTypes: true,
};

function escapeName(name: string): string {
  return `"${name}"`;
}

function escapeMySQLName(name: string): string {
  return `\`${name}\``;
}

function escapeSQLServerName(name: string): string {
  return `[${name}]`;
}

function getEscaper(dbType: DatabaseType): (name: string) => string {
  switch (dbType) {
    case DatabaseType.MYSQL:
    case DatabaseType.MARIADB:
      return escapeMySQLName;
    case DatabaseType.SQL_SERVER:
      return escapeSQLServerName;
    default:
      return escapeName;
  }
}

function formatColumnType(field: DBField, dbType: DatabaseType): string {
  const typeName = field.type.name.toLowerCase();
  let typeStr = typeName;

  if (dbType === DatabaseType.SQLITE) {
    return "TEXT";
  }

  if (
    field.characterMaximumLength &&
    (typeName === "varchar" ||
      typeName === "char" ||
      typeName === "nvarchar" ||
      typeName === "nchar")
  ) {
    typeStr = `${typeName}(${field.characterMaximumLength})`;
  } else if (
    field.precision !== null &&
    field.precision !== undefined &&
    field.scale !== null &&
    field.scale !== undefined
  ) {
    if (typeName === "decimal" || typeName === "numeric") {
      typeStr = `${typeName}(${field.precision}, ${field.scale})`;
    }
  } else if (field.precision !== null && field.precision !== undefined) {
    if (typeName === "decimal" || typeName === "numeric") {
      typeStr = `${typeName}(${field.precision})`;
    }
  }

  return typeStr;
}

function generateAutoIncrementSyntax(dbType: DatabaseType): string {
  switch (dbType) {
    case DatabaseType.POSTGRESQL:
      return " GENERATED BY DEFAULT AS IDENTITY";
    case DatabaseType.MYSQL:
    case DatabaseType.MARIADB:
      return " AUTO_INCREMENT";
    case DatabaseType.SQL_SERVER:
      return " IDENTITY(1,1)";
    case DatabaseType.ORACLE:
      return " GENERATED BY DEFAULT AS IDENTITY";
    case DatabaseType.SQLITE:
      return " AUTOINCREMENT";
    default:
      return " AUTO_INCREMENT";
  }
}

function generateBooleanType(dbType: DatabaseType): string {
  switch (dbType) {
    case DatabaseType.MYSQL:
    case DatabaseType.MARIADB:
      return "TINYINT(1)";
    case DatabaseType.SQL_SERVER:
      return "BIT";
    case DatabaseType.SQLITE:
      return "INTEGER";
    default:
      return "BOOLEAN";
  }
}

function formatDefault(field: DBField, _dbType: DatabaseType): string {
  if (field.default === null || field.default === undefined) return "";

  const val = field.default;
  const typeName = field.type.name.toLowerCase();

  if (typeName === "boolean" || typeName === "bool") {
    if (val === "true" || val === "1") return " DEFAULT TRUE";
    if (val === "false" || val === "0") return " DEFAULT FALSE";
  }

  if (
    val === "CURRENT_TIMESTAMP" ||
    val === "now()" ||
    val === "CURRENT_DATE" ||
    val === "CURRENT_TIME"
  ) {
    return ` DEFAULT ${val}`;
  }

  if (val.startsWith("(") && val.endsWith(")")) {
    return ` DEFAULT ${val}`;
  }

  if (typeName === "json" || typeName === "jsonb") {
    return ` DEFAULT '${val}'`;
  }

  return ` DEFAULT '${val}'`;
}

function generateCustomTypes(
  customTypes: DBCustomType[],
  dbType: DatabaseType,
): string[] {
  const statements: string[] = [];

  for (const ct of customTypes) {
    if (ct.kind === DBCustomTypeKind.enum && ct.values) {
      const schemaPrefix = ct.schema ? `${ct.schema}.` : "";
      switch (dbType) {
        case DatabaseType.POSTGRESQL:
          statements.push(
            `CREATE TYPE ${schemaPrefix}${escapeName(ct.name)} AS ENUM (\n${ct.values.map((v) => `    '${v}'`).join(",\n")}\n);`,
          );
          break;
        case DatabaseType.MYSQL:
        case DatabaseType.MARIADB:
          statements.push(
            `CREATE TYPE ${schemaPrefix}${escapeMySQLName(ct.name)} AS ENUM (\n${ct.values.map((v) => `    '${v}'`).join(",\n")}\n);`,
          );
          break;
        case DatabaseType.SQL_SERVER:
          statements.push(
            `CREATE TYPE ${schemaPrefix}${escapeSQLServerName(ct.name)} AS NVARCHAR(255);`,
          );
          break;
        default:
          break;
      }
    }
  }

  return statements;
}

function generateCreateTable(
  table: DBTable,
  dbType: DatabaseType,
  escapeId: (name: string) => string,
): string {
  const schemaPrefix = table.schema ? `${table.schema}.` : "";
  const lines: string[] = [];

  for (const field of table.fields) {
    let colDef = `    ${escapeId(field.name)} `;

    if (
      field.type.name.toLowerCase() === "boolean" ||
      field.type.name.toLowerCase() === "bool"
    ) {
      colDef += generateBooleanType(dbType);
    } else {
      colDef += formatColumnType(field, dbType);
    }

    if (field.primaryKey && dbType === DatabaseType.POSTGRESQL) {
      colDef += " SERIAL";
    }

    if (field.increment) {
      colDef += generateAutoIncrementSyntax(dbType);
    }

    if (!field.nullable && !field.primaryKey) {
      colDef += " NOT NULL";
    }

    if (field.unique && !field.primaryKey) {
      colDef += " UNIQUE";
    }

    colDef += formatDefault(field, dbType);

    lines.push(colDef);
  }

  const pkFields = table.fields.filter((f) => f.primaryKey);
  if (pkFields.length > 0) {
    const pkCols = pkFields.map((f) => escapeId(f.name)).join(", ");
    lines.push(`    PRIMARY KEY (${pkCols})`);
  }

  return `CREATE TABLE ${schemaPrefix}${escapeId(table.name)} (\n${lines.join(",\n")}\n);`;
}

function resolveSourceFieldName(table: DBTable, fieldId: string): string {
  return table.fields.find((f) => f.id === fieldId)?.name ?? fieldId;
}

function generateInlineForeignKeys(
  table: DBTable,
  relationships: DBRelationship[],
  tableMap: Map<string, DBTable>,
  _dbType: DatabaseType,
  escapeId: (name: string) => string,
): string[] {
  const statements: string[] = [];
  const schemaPrefix = table.schema ? `${table.schema}.` : "";

  for (const field of table.fields) {
    const fk = relationships.find(
      (r) => r.targetTableId === table.id && r.targetFieldId === field.id,
    );
    if (!fk) continue;

    const sourceTable = tableMap.get(fk.sourceTableId);
    if (!sourceTable) continue;

    const sourceSchema = sourceTable.schema || table.schema || null;
    const sourceSchemaPrefix = sourceSchema ? `${sourceSchema}.` : "";

    const constraintName = `fk_${table.name}_${field.name}`;
    const onDelete =
      fk.targetCardinality === "one" && fk.sourceCardinality === "many"
        ? " ON DELETE CASCADE"
        : "";

    statements.push(
      `ALTER TABLE ${schemaPrefix}${escapeId(table.name)} ADD CONSTRAINT ${escapeId(constraintName)} FOREIGN KEY (${escapeId(field.name)}) REFERENCES ${sourceSchemaPrefix}${escapeId(sourceTable.name)} (${escapeId(resolveSourceFieldName(sourceTable, fk.sourceFieldId))})${onDelete};`,
    );
  }

  return statements;
}

function generateIndexes(
  table: DBTable,
  dbType: DatabaseType,
  escapeId: (name: string) => string,
): string[] {
  const statements: string[] = [];
  const schemaPrefix = table.schema ? `${table.schema}.` : "";

  for (const idx of table.indexes) {
    const fields = idx.fieldIds
      .map((fid) => table.fields.find((f) => f.id === fid))
      .filter((f): f is DBField => f !== undefined);

    if (fields.length === 0) continue;

    const cols = fields.map((f) => escapeId(f.name)).join(", ");
    const unique = idx.unique ? "UNIQUE " : "";
    let indexType = "";
    if (
      idx.type &&
      dbType === DatabaseType.POSTGRESQL &&
      idx.type !== "btree"
    ) {
      indexType = ` USING ${idx.type.toUpperCase()}`;
    }

    statements.push(
      `CREATE ${unique}INDEX ${escapeId(idx.name)} ON ${schemaPrefix}${escapeId(table.name)}${indexType} (${cols});`,
    );
  }

  return statements;
}

function generateViews(
  table: DBTable,
  _dbType: DatabaseType,
  escapeId: (name: string) => string,
): string[] {
  if (!table.isView) return [];

  const schemaPrefix = table.schema ? `${table.schema}.` : "";
  const keyword = table.isMaterializedView ? "MATERIALIZED VIEW" : "VIEW";
  const cols = table.fields.map((f) => escapeId(f.name)).join(", ");

  return [
    `CREATE ${keyword} ${schemaPrefix}${escapeId(table.name)} AS\nSELECT ${cols}\nFROM /* source tables */;`,
  ];
}

export function generateTableSQL(
  table: DBTable,
  databaseType: DatabaseType = DatabaseType.POSTGRESQL,
): string {
  const escapeId = getEscaper(databaseType);
  return generateCreateTable(table, databaseType, escapeId);
}

export function generateSQL(
  diagram: Diagram,
  options: GenerateSQLOptions = {},
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const dbType = diagram.databaseType || DatabaseType.POSTGRESQL;
  const escapeId = getEscaper(dbType);
  const parts: string[] = [];

  const tables = diagram.tables ?? [];
  const relationships = diagram.relationships ?? [];
  const customTypes = diagram.customTypes ?? [];

  const tableMap = new Map<string, DBTable>();
  for (const t of tables) {
    tableMap.set(t.id, t);
  }

  if (opts.includeCustomTypes && customTypes.length > 0) {
    const typeStatements = generateCustomTypes(customTypes, dbType);
    if (typeStatements.length > 0) {
      parts.push(...typeStatements);
      parts.push("");
    }
  }

  const regularTables = tables.filter((t) => !t.isView);
  const viewTables = tables.filter((t) => t.isView);

  for (const table of regularTables) {
    const stmt = generateCreateTable(table, dbType, escapeId);
    parts.push(stmt);
    parts.push("");
  }

  if (opts.includeForeignKeys) {
    for (const table of regularTables) {
      const fkStatements = generateInlineForeignKeys(
        table,
        relationships,
        tableMap,
        dbType,
        escapeId,
      );
      if (fkStatements.length > 0) {
        parts.push(...fkStatements);
        parts.push("");
      }
    }
  }

  if (opts.includeIndexes) {
    for (const table of regularTables) {
      const idxStatements = generateIndexes(table, dbType, escapeId);
      if (idxStatements.length > 0) {
        parts.push(...idxStatements);
        parts.push("");
      }
    }
  }

  if (viewTables.length > 0) {
    for (const table of viewTables) {
      const viewStmts = generateViews(table, dbType, escapeId);
      if (viewStmts.length > 0) {
        parts.push(...viewStmts);
        parts.push("");
      }
    }
  }

  return parts.join("\n").trim();
}
