/**
 * This file is part of the SchemaVis project.
 * Copyright (C) 2025 Akshat Kotpalliwar (IntegerAlex)
 * Licensed under the GNU Affero General Public License v3.0 or later.
 */

import type { Competitor } from './types';

export const competitors: Competitor[] = [
  {
    id: 'drawsql',
    name: 'DrawSQL',
    website: 'https://drawsql.app',
    logoUrl: 'https://drawsql.app/favicon.ico',
    description: 'Market-leading database visualization tool with polished UI and excellent visual output.',
    strengths: [
      'Mature and production-ready',
      'Excellent visual polish and consistency',
      'Fast performance with large diagrams',
      'Beautiful table node design',
      'Clean, readable relationship lines',
      'Professional color schemes',
      'Excellent mobile support',
      'Real-time collaboration (Pro version)',
      'Over 200 database diagram templates',
    ],
    weaknesses: [
      'Free tier limited to public diagrams only',
      'Not open source',
      'Real-time collaboration requires paid plan',
      'Limited customization options',
    ],
    pricing: 'Free tier + Paid ($15+/month)',
    openSource: false,
    collaboration: true, // Available in Pro version
    visualQuality: 5,
    relationshipDisplay: 'Excellent',
    modernUI: true,
    freeTier: true, // Free tier exists but limited to public diagrams
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server'],
    uniqueStrengths: [
      'Market leader with proven track record',
      'Polished, professional output',
      'Optimized for presentations',
    ],
    bestFor: [
      'Production-ready visualization needs',
      'Professional presentations',
      'Solo developers or small teams',
      'Users who prioritize visual polish',
    ],
  },
  {
    id: 'dbdiagram',
    name: 'dbdiagram.io',
    website: 'https://dbdiagram.io',
    logoUrl: 'https://dbdiagram.io/favicon.ico',
    description: 'DSL-based database diagramming tool with a free tier and good visual output.',
    strengths: [
      'Free tier available',
      'DSL-based approach (easy version control)',
      'Good visual quality',
      'Modern UI',
      'Export to various formats',
    ],
    weaknesses: [
      'DSL learning curve',
      'Limited with complex schemas',
      'Basic collaboration (not full real-time)',
      'Not open source',
      'Free tier limited to 10 diagrams',
    ],
    pricing: 'Free tier (10 diagrams) + Paid ($9/month)',
    openSource: false,
    collaboration: false, // Basic sharing/team access, not full real-time
    visualQuality: 4,
    relationshipDisplay: 'Good',
    modernUI: true,
    freeTier: true,
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQL Server', 'SQLite'],
    uniqueStrengths: [
      'DSL approach for version control',
      'Good free tier',
      'Easy to learn',
    ],
    bestFor: [
      'Users who prefer text-based definitions',
      'Version control workflows',
      'Simple to medium complexity schemas',
    ],
  },
  {
    id: 'drawdb',
    name: 'DrawDB',
    website: 'https://drawdb.com',
    logoUrl: 'https://drawdb.com/favicon.ico',
    description: 'Open source database visualization tool with good visual quality.',
    strengths: [
      'Open source',
      'Good visual quality',
      'Modern UI',
      'Free to use',
    ],
    weaknesses: [
      'Smaller community',
      'Limited collaboration features',
      'Less polished than commercial alternatives',
    ],
    pricing: 'Free (Open Source)',
    openSource: true,
    collaboration: false,
    visualQuality: 4,
    relationshipDisplay: 'Very Good',
    modernUI: true,
    freeTier: true,
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQLite'],
    uniqueStrengths: [
      'Open source',
      'Community-driven development',
      'Good visual quality for open source tool',
    ],
    bestFor: [
      'Open source advocates',
      'Users who want to customize',
      'Community contributors',
    ],
  },
  {
    id: 'dbeaver',
    name: 'DBeaver',
    website: 'https://dbeaver.io',
    logoUrl: 'https://dbeaver.io/favicon.ico',
    description: 'Universal database tool with visualization capabilities, primarily a desktop application.',
    strengths: [
      'Free and open source',
      'Universal database support',
      'Powerful database management features',
      'Extensive plugin ecosystem',
    ],
    weaknesses: [
      'Desktop app (not web-based)',
      'Complex interface',
      'Fair visual quality',
      'Not focused on visualization',
      'Steeper learning curve',
    ],
    pricing: 'Free (Community Edition)',
    openSource: true,
    collaboration: false,
    visualQuality: 3,
    relationshipDisplay: 'Fair',
    modernUI: false,
    freeTier: true,
    databaseSupport: ['All major databases'],
    uniqueStrengths: [
      'Comprehensive database tool',
      'Universal database support',
      'Free and open source',
    ],
    bestFor: [
      'Database administrators',
      'Users who need full database management',
      'Desktop application preference',
    ],
  },
  {
    id: 'sqldbm',
    name: 'SqlDBM',
    website: 'https://sqldbm.com',
    logoUrl: 'https://sqldbm.com/favicon.ico',
    description: 'Professional database modeling tool with excellent visualization capabilities.',
    strengths: [
      'Excellent visual quality',
      'Professional database modeling features',
      'Good relationship display',
      'Modern UI',
    ],
    weaknesses: [
      'Paid tool (may have limited free trial)',
      'Not open source',
      'No permanent free tier',
      'No real-time collaboration',
    ],
    pricing: 'Paid (may offer trial)',
    openSource: false,
    collaboration: false,
    visualQuality: 4,
    relationshipDisplay: 'Excellent',
    modernUI: true,
    freeTier: false,
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQL Server', 'Oracle'],
    uniqueStrengths: [
      'Professional modeling features',
      'Excellent relationship visualization',
      'Enterprise-ready',
    ],
    bestFor: [
      'Enterprise users',
      'Professional database modeling',
      'Complex schema design',
    ],
  },
  {
    id: 'schemaspy',
    name: 'SchemaSpy',
    website: 'https://schemaspy.org',
    logoUrl: 'https://schemaspy.org/favicon.ico',
    description: 'Open source database schema analysis tool with basic visualization.',
    strengths: [
      'Free and open source',
      'Comprehensive schema analysis',
      'Generates HTML documentation',
    ],
    weaknesses: [
      'Basic visual quality',
      'Outdated UI',
      'Command-line tool',
      'No interactive editing',
      'Limited relationship display',
    ],
    pricing: 'Free (Open Source)',
    openSource: true,
    collaboration: false,
    visualQuality: 2,
    relationshipDisplay: 'Basic',
    modernUI: false,
    freeTier: true,
    databaseSupport: ['PostgreSQL', 'MySQL', 'Oracle', 'SQL Server', 'SQLite'],
    uniqueStrengths: [
      'Comprehensive schema analysis',
      'Documentation generation',
      'Free and open source',
    ],
    bestFor: [
      'Schema documentation needs',
      'Command-line workflows',
      'Automated documentation generation',
    ],
  },
  {
    id: 'azimutt',
    name: 'Azimutt',
    website: 'https://azimutt.app',
    logoUrl: 'https://azimutt.app/favicon.ico',
    description: 'Open source database schema explorer with good visualization and collaboration features.',
    strengths: [
      'Open source',
      'Good visual quality',
      'Real-time collaboration',
      'Modern UI',
      'Freemium model',
    ],
    weaknesses: [
      'Smaller community than commercial tools',
      'Less polished than market leaders',
    ],
    pricing: 'Free (Open Source) + Paid plans',
    openSource: true,
    collaboration: true,
    visualQuality: 4,
    relationshipDisplay: 'Good',
    modernUI: true,
    freeTier: true,
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server'],
    uniqueStrengths: [
      'Open source with collaboration',
      'Good balance of features',
      'Active development',
    ],
    bestFor: [
      'Open source advocates who need collaboration',
      'Teams wanting open source solution',
      'Users who value transparency',
    ],
  },
  {
    id: 'chartsdb',
    name: 'ChartDB',
    website: 'https://chartdb.io',
    logoUrl: 'https://chartdb.io/favicon.ico',
    description: 'Open source database visualization tool with excellent visual quality, focused on PostgreSQL.',
    strengths: [
      'Excellent visual quality',
      'Open source (AGPL)',
      'Modern React architecture',
      'Free to use',
      'Excellent relationship display',
    ],
    weaknesses: [
      'PostgreSQL-focused (limited multi-database support)',
      'No real-time collaboration',
      'Smaller community',
    ],
    pricing: 'Free (Open Source)',
    openSource: true,
    collaboration: false,
    visualQuality: 5,
    relationshipDisplay: 'Excellent',
    modernUI: true,
    freeTier: true,
    databaseSupport: ['PostgreSQL', 'MySQL', 'SQLite'],
    uniqueStrengths: [
      'Excellent visuals for open source tool',
      'Modern architecture',
      'AGPL licensed',
    ],
    bestFor: [
      'PostgreSQL users',
      'Open source advocates',
      'Users who prioritize visual quality',
    ],
  },
];

export const schemavisCompetitor: Competitor = {
  id: 'schemavis',
  name: 'SchemaVis',
  website: 'https://schemavis.gossorg.in',
  description: 'Alpha-stage open source database visualization tool focused on modern visualization with planned collaboration features.',
  strengths: [
    'Open source (AGPL)',
    'Modern React architecture',
    'Free to use',
    'Multi-database support',
    'Real-time collaboration (planned)',
  ],
  weaknesses: [
    'Alpha stage (not production-ready)',
    'Visual quality needs refinement',
    'Performance can be slow with large diagrams',
    'Basic mobile support',
    'Steeper learning curve due to alpha roughness',
  ],
  pricing: 'Free',
  openSource: true,
  collaboration: false, // Not yet available; planned for future release
  visualQuality: 3,
  relationshipDisplay: 'Good',
  modernUI: true,
  freeTier: true,
  databaseSupport: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server'],
  uniqueStrengths: [
    'Open source with planned real-time collaboration',
    'Modern architecture',
    'User feedback shapes development',
  ],
  bestFor: [
    'Early adopters',
    'Open source advocates',
    'Users who want to influence development',
  ],
};

export function getCompetitorById(id: string): Competitor | undefined {
  return competitors.find((c) => c.id === id);
}

export function getAllCompetitors(): Competitor[] {
  return competitors;
}

